### ISSUE TITLE
Permettre de faire passer autre chose que des subreads

### ISSUE THREAD

**Issue by mdeloger** [bioinfo-pf-curie/pyvif#1]
@ddesvillechabrol ,

pyvif parse les noms des reads et il s'attend à la structure typique des subreads, à savoir : @name/zmw/start_end.
Or ça serait bien qu'il puisse aller jusqu'au bout même si on lui donne : 

1) des CCS : @name/zmw/"ccs"
2) des sorties d'assemblage : @name|"arrow"

Histoire de le rendre le plus générique possible :-)

Merci ++

**Comment by ddesvillechabrol** [comment]
Done ! Tu peux pull la master :)

**Comment by mdeloger** [comment]
Merci
Done mais fail :-P

(/bioinfo/local/build/Centos/envs_conda/pyvif) -bash-4.2$ cat logs/Assembly_coverage_mincov2_seedcov2_R1-465622_WGS_all5datasets/pyvif.log
2018-10-17 09:12:25 - INFO     Scanning input file. Please wait.
2018-10-17 09:12:25 - INFO     Input file contains valid 14 alignments.
2018-10-17 09:12:25 - INFO     Scanning input file. Please wait.
[W::hts_idx_load2] The index file is older than the data file: control_alignment/Assembly_coverage_mincov2_seedcov2_R1-465622_WGS_all5datasets.control.bam.bai
2018-10-17 09:12:25 - INFO     Input file contains valid 115 alignments.
2018-10-17 09:12:25 - INFO     Scanning input file. Please wait.
[W::hts_idx_load2] The index file is older than the data file: human_alignment/Assembly_coverage_mincov2_seedcov2_R1-465622_WGS_all5datasets.human.bam.bai
2018-10-17 09:12:25 - INFO     Input file contains valid 429 alignments.
2018-10-17 09:12:25 - INFO     Breakpoint research is running...
2018-10-17 09:12:25 - INFO     3 breakpoints are found.
/bioinfo/local/build/Centos/envs_conda/pyvif/lib/python3.6/site-packages/pandas/core/ops.py:1167: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)
Traceback (most recent call last):
  File "/bioinfo/local/build/Centos/envs_conda/pyvif/bin/pyvif", line 11, in <module>
    load_entry_point('pyvif==0.1.0', 'console_scripts', 'pyvif')()
  File "/bioinfo/local/build/Centos/envs_conda/pyvif/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/bioinfo/local/build/Centos/envs_conda/pyvif/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/bioinfo/local/build/Centos/envs_conda/pyvif/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/bioinfo/local/build/Centos/envs_conda/pyvif/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/bioinfo/local/build/Centos/envs_conda/pyvif/lib/python3.6/site-packages/pyvif-0.1.0-py3.6.egg/pyvif/cli.py", line 70, in main
    bp_finder.clustering_breakpoints()
  File "/bioinfo/local/build/Centos/envs_conda/pyvif/lib/python3.6/site-packages/pyvif-0.1.0-py3.6.egg/pyvif/bp_finder.py", line 210, in clustering_breakpoints
    cond = self.bps['bpstart_human'] != 'Unknown'
  File "/bioinfo/local/build/Centos/envs_conda/pyvif/lib/python3.6/site-packages/pandas/core/ops.py", line 1283, in wrapper
    res = na_op(values, other)
  File "/bioinfo/local/build/Centos/envs_conda/pyvif/lib/python3.6/site-packages/pandas/core/ops.py", line 1169, in na_op
    raise TypeError("invalid type comparison")
TypeError: invalid type comparison

**Comment by ddesvillechabrol** [comment]
A priori c'est parce que tes résultats sont trop parfait. Tu n'as pas d'alignement inconnu.
J'ai fixé le bug normalement.

**Comment by mdeloger** [comment]
Parfait, ça marche !

Merci ;-)
